In [1]:
from __future__ import division

import scipy as sp
import scipy.sparse as sprs
import scipy.spatial
import scipy.sparse.linalg


In [2]:
import numpy as np
page = [[0,0,0,.5,0],
        [1,0,0,0,0],
        [0,.5,0,0,1],
        [0,.5,1,0,0],
        [0,0,0,.5,0]]
page1 = np.array(page)
print(page1)
r_1 = page[0][3]
r_2 = page[1][0]
r_3a = page[2][1]
r_3b = page[2][4]
r_4a = page[3][1]
r_4b = page[3][2]
r_5 = page[4][3]

n = 5
c =.85
#c = float(input("Enter decay value(c): "))

r = [0,0,0,0,0]
r[0] = 1/n
r[1] = 1/n
r[2] = 1/n
r[3] = 1/n
r[4] = 1/n

for x in range(30): #30 is the no. of iterations
    print(np.array(r))
    a = c * r[3] * r_1 + ((1-c)/n)
    b = c * r[0] * r_2 + ((1-c)/n)
    s = (c * r[1] * r_3a) + (c * r[4] * r_3b) + ((1-c)/n)
    d = (c * r[1] * r_4a) + (c * r[2] * r_4b) + ((1-c)/n)
    e = c * r[3] * r_5 + ((1-c)/n)
    r[0] = round(a,4)
    r[1] = round(b,4)
    r[2] = round(s,4)
    r[3] = round(d,4)
    r[4] = round(e,4)

[[0.  0.  0.  0.5 0. ]
 [1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  1. ]
 [0.  0.5 1.  0.  0. ]
 [0.  0.  0.  0.5 0. ]]
[0.2 0.2 0.2 0.2 0.2]
[0.115 0.2   0.285 0.285 0.115]
[0.1511 0.1278 0.2128 0.3573 0.1511]
[0.1819 0.1584 0.2127 0.2652 0.1819]
[0.1427 0.1846 0.2519 0.2781 0.1427]
[0.1482 0.1513 0.2297 0.3226 0.1482]
[0.1671 0.156  0.2203 0.2895 0.1671]
[0.153  0.172  0.2383 0.2836 0.153 ]
[0.1505 0.16   0.2331 0.3057 0.1505]
[0.1599 0.1579 0.2259 0.2961 0.1599]
[0.1558 0.1659 0.233  0.2891 0.1558]
[0.1529 0.1624 0.2329 0.2986 0.1529]
[0.1569 0.16   0.229  0.297  0.1569]
[0.1562 0.1634 0.2314 0.2927 0.1562]
[0.1544 0.1628 0.2322 0.2961 0.1544]
[0.1558 0.1612 0.2304 0.2966 0.1558]
[0.1561 0.1624 0.2309 0.2944 0.1561]
[0.1551 0.1627 0.2317 0.2953 0.1551]
[0.1555 0.1618 0.231  0.2961 0.1555]
[0.1558 0.1622 0.2309 0.2951 0.1558]
[0.1554 0.1624 0.2314 0.2952 0.1554]
[0.1555 0.1621 0.2311 0.2957 0.1555]
[0.1557 0.1622 0.2311 0.2953 0.1557]
[0.1555 0.1623 0.2313 0.2954 0.1555]
[0.1555 0.1622 0

### Creating a proc for the same

In [3]:
def pagerank_power(A, p=0.85, max_iter=30,
                   tol=1e-06, personalize=None, reverse=False):
    """ Calculates PageRank given a csr graph

    Inputs:
    -------
    A: a csr graph.
    p: decay factor
    max_iter: maximum number of iterations
    personlize: if not None, should be an array with the size of the nodes
                containing probability distributions.
                It will be normalized automatically.
    reverse: If true, returns the reversed-PageRank

    Returns:
    --------
    PageRank Scores for the nodes

    """
    # In Moler's algorithm, $$G_{ij}$$ represents the existences of an edge
    # from node $$j$$ to $$i$$, while we have assumed the opposite!
    if reverse:
        A = A.T

    n, _ = A.shape
    r = sp.asarray(A.sum(axis=1)).reshape(-1)

    k = r.nonzero()[0]

    D_1 = sprs.csr_matrix((1 / r[k], (k, k)), shape=(n, n))

    if personalize is None:
        personalize = sp.ones(n)
    personalize = personalize.reshape(n, 1)
    s = (personalize / personalize.sum()) * n

    z_T = (((1 - p) * (r != 0) + (r == 0)) / n)[sp.newaxis, :]
    W = p * A.T @ D_1

    x = s
    oldx = sp.zeros((n, 1))

    iteration = 0

    while sp.linalg.norm(x - oldx) > tol:
        oldx = x
        x = W @ x + s @ (z_T @ x)
        iteration += 1
        if iteration >= max_iter:
            break
    x = x / sum(x)

    return x.reshape(-1)

In [4]:
from numpy.testing import assert_allclose
import unittest
import scipy.sparse as sparse

In [5]:
n1=5
edges1 = sp.array([[1, 2],
                           [2, 3],
                           [2, 4],
                           [3, 4],
                           [4, 1],
                           [4, 5],
                           [5, 1]])

weights1 = [1,0.5,0.5,1,0.5,0.5,1]

personalize1 = sp.array([0.1556,0.1622,0.2312,0.2955,0.1556])

G1 = sparse.csr_matrix((weights1, (edges1[:, 0], edges1[:, 1])))

/var/folders/xd/7xbbxhs53f36m2cf0d1gf7jm0000gp/T/ipykernel_5578/3449831715.py:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  edges1 = sp.array([[1, 2],
/var/folders/xd/7xbbxhs53f36m2cf0d1gf7jm0000gp/T/ipykernel_5578/3449831715.py:12: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  personalize1 = sp.array([0.1556,0.1622,0.2312,0.2955,0.1556])


In [6]:
calculated_pagerank = pagerank_power(G1)
assert_allclose(calculated_pagerank, 0.85, rtol=0, atol=1e-04)

/var/folders/xd/7xbbxhs53f36m2cf0d1gf7jm0000gp/T/ipykernel_5578/1882285758.py:26: DeprecationWarning: scipy.asarray is deprecated and will be removed in SciPy 2.0.0, use numpy.asarray instead
  r = sp.asarray(A.sum(axis=1)).reshape(-1)
/var/folders/xd/7xbbxhs53f36m2cf0d1gf7jm0000gp/T/ipykernel_5578/1882285758.py:33: DeprecationWarning: scipy.ones is deprecated and will be removed in SciPy 2.0.0, use numpy.ones instead
  personalize = sp.ones(n)
/var/folders/xd/7xbbxhs53f36m2cf0d1gf7jm0000gp/T/ipykernel_5578/1882285758.py:41: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
  oldx = sp.zeros((n, 1))


AssertionError: 
Not equal to tolerance rtol=0, atol=0.0001

Mismatched elements: 6 / 6 (100%)
Max absolute difference: 0.82087379
Max relative difference: 0.96573387
 x: array([0.029126, 0.240772, 0.23378 , 0.128482, 0.237693, 0.130147])
 y: array(0.85)